# Copyright (c) 2021 Qianyun, Inc. All rights reserved.

# ucloud
UC_INSTANCE_STATE_ACTIVE = 'Running'
UC_INSTANCE_STATE_STARTING = 'Starting'
UC_INSTANCE_STATE_STOPPED = 'Stopped'
UC_INSTANCE_STATE_INITIALIZING = 'Initializing'
UC_INSTANCE_STATE_STOPPING = 'Stopping'
UC_INSTANCE_STATE_REBOOTING = 'Rebooting'
UC_INSTANCE_STATE_INSTALL_FAIL = 'Install Fail'

UC_VOLUME_STATE_AVAILABLE = 'Available'
UC_VOLUME_STATE_INITIALIZATING = 'Initializating'
UC_VOLUME_STATE_ATTACHING = 'Attaching'
UC_VOLUME_STATE_IN_USE = 'InUse'
UC_VOLUME_STATE_DETACHING = 'Detaching'
UC_VOLUME_STATE_CLONING = 'Cloning'
UC_VOLUME_STATE_RESTORING = 'Restoring'
UC_VOLUME_STATE_RESTORE_FAILED = 'RestoreFailed'
UC_VOLUME_STATE_FAILED = 'Failed'

UC_VOLUME_TYPE = 'CLOUD_SSD'
MachineType = 'O'  # current ucloud only support this
