# Copyright (c) 2021 Qianyun, Inc. All rights reserved.

GCP_INSTANCE_STATE_PROVISIONING = 'PROVISIONING'
GCP_INSTANCE_STATE_STARTING = 'STAGING'
GCP_INSTANCE_STATE_RUNNING = 'RUNNING'
GCP_INSTANCE_STATE_STOPPING = 'STOPPING'
GCP_INSTANCE_STATE_STOPPED = 'TERMINATED'
GCP_INSTANCE_STATE_SUSPENDING = 'SUSPENDING'
GCP_INSTANCE_STATE_SUSPENDED = 'SUSPENDED'

GCP_VOLUME_STATE_AVAILABLE = 'READY'
GCP_VOLUME_STATE_CREATING = 'CREATING'
GCP_VOLUME_STATE_DELETING = 'DELETING'
GCP_VOLUME_STATE_BEING_COPIED = 'RESTORING'
GCP_VOLUME_STATE_ERROR = 'FAILED'
