# Copyright (c) 2021 Qianyun, Inc. All rights reserved.

UCLOUD_REGION_NAME = {
    'cn-bj1': '北京一',
    'cn-bj2': '北京二',
    'cn-sh': '上海金融云',
    'cn-sh2': '上海二',
    'cn-gd': '广州',
    'cn-qz': '福建',
    'cn-hz': '杭州',
    'hk': '香港',
    'us-ca': '洛杉矶',
    'us-ws': '华盛顿',
    'ge-fra': '法兰克福',
    'th-bkk': '曼谷',
    'kr-seoul': '首尔',
    'sg': '新加坡',
    'tw-tp': '台北',
    'tw-kh': '高雄',
    'jpn-tky': '东京',
    'rus-mosc': '莫斯科',
    'uae-dubai': '迪拜',
    'idn-jakarta': '雅加达',
    'ind-mumbai': '孟买',
    'bra-saopaulo': '圣保罗',
    'uk-london': '伦敦',
    'afr-nigeria': '拉各斯',
    'vn-sng': '胡志明市',
    'ph-mnl': '马尼拉'
}

UCLOUD_ZONE_NAME = {
    'cn-sh-02': '上海金融云可用区B',
    'hk-01': '香港可用区A',
    'kr-seoul-01': '首尔可用区A',
    'cn-sh2-01': '上海二可用区A',
    'uae-dubai-01': '迪拜可用区A',
    'ind-mumbai-01': '孟买可用区A',
    'cn-sh-01': '上海金融云可用区A',
    'uk-london-01': '伦敦可用区A',
    'cn-qz-01': '福建GPU可用区A',
    'jpn-tky-01': '东京可用区A',
    'us-ca-01': '洛杉矶可用区A',
    'bra-saopaulo-01': '圣保罗可用区A',
    'idn-jakarta-01': '雅加达可用区A',
    'cn-sh2-03': '上海二可用区C',
    'vn-sng-01': '胡志明市可用区A',
    'afr-nigeria-01': '拉各斯可用区A',
    'cn-bj2-04': '北京二可用区D',
    'us-ws-01': '华盛顿可用区A',
    'cn-sh2-02': '上海二可用区B',
    'cn-gd2-01': '广州二可用区A',
    'tw-tp2-01': '台北二可用区A',
    'rus-mosc-01': '莫斯科',
    'cn-bj2-03': '北京二可用区C',
    'th-bkk-01': '曼谷可用区A',
    'th-bkk-02': '曼谷可用区B',
    'cn-bj2-02': '北京二可用区B',
    'sg-01': '新加坡可用区A',
    'tw-kh-01': '高雄可用区A',
    'ge-fra-01': '法兰克福可用区A',
    'hk-02': '香港可用区B',
    'cn-sh-03': '上海金融云可用区C',
    'cn-bj1-01': '北京一可用区A',
    'cn-gd-02': '广州可用区B',
    'cn-bj2-05': '北京二可用区E',
    'tw-tp-01': '台北可用区A',
    'ph-mnl-01': '马尼拉可用区A'
}
